$(document).ready(function(){
	//第一个位置
	$("#box-item1").bind("mouseenter",function(){
		$("#panel-item1").css("backgroundColor","rgb(247,247,247)");
		$("#angle1").css({
			"display":"inline-block"
		});
	});
	$("#box-item1").bind("mouseleave",function(){
		$("#panel-item1").css("background","rgba(255,255,255,.97)");
		$("#angle1").css({
			"display":"none"
		});
	});
	$("#panel-item1").bind("mouseenter",function(){
		$("#panel-item1").css("background","rgb(247,247,247)");
		$("#angle1").css({
			"display":"inline-block"
		});
	});
	$("#panel-item1").bind("mouseleave",function(){
		$("#panel-item1").css("background","rgba(255,255,255,.97)");
		$("#angle1").css({
			"display":"none"
		});
	});

	//第二个位置
	$("#box-item2").bind("mouseenter",function(){
		$("#panel-item2").css("backgroundColor","rgb(247,247,247)");
		$("#angle2").css({
			"display":"inline-block"
		});
	});
	$("#box-item2").bind("mouseleave",function(){
		$("#panel-item2").css("background","rgba(255,255,255,.97)");
		$("#angle2").css({
			"display":"none"
		});
	});
	$("#panel-item2").bind("mouseenter",function(){
		$("#panel-item2").css("background","rgb(247,247,247)");
		$("#angle2").css({
			"display":"inline-block"
		});
	});
	$("#panel-item2").bind("mouseleave",function(){
		$("#panel-item2").css("background","rgba(255,255,255,.97)");
		$("#angle2").css({
			"display":"none"
		});
	});

	//第三个位置
	$("#box-item3").bind("mouseenter",function(){
		$("#panel-item3").css("backgroundColor","rgb(247,247,247)");
		$("#angle3").css({
			"display":"inline-block"
		});
	});
	$("#box-item3").bind("mouseleave",function(){
		$("#panel-item3").css("background","rgba(255,255,255,.97)");
		$("#angle3").css({
			"display":"none"
		});
	});
	$("#panel-item3").bind("mouseenter",function(){
		$("#panel-item3").css("background","rgb(247,247,247)");
		$("#angle3").css({
			"display":"inline-block"
		});
	});
	$("#panel-item3").bind("mouseleave",function(){
		$("#panel-item3").css("background","rgba(255,255,255,.97)");
		$("#angle3").css({
			"display":"none"
		});
	});

	//第四个位置
	$("#box-item4").bind("mouseenter",function(){
		$("#panel-item4").css("backgroundColor","rgb(247,247,247)");
		$("#angle4").css({
			"display":"inline-block"
		});
	});
	$("#box-item4").bind("mouseleave",function(){
		$("#panel-item4").css("background","rgba(255,255,255,.97)");
		$("#angle4").css({
			"display":"none"
		});
	});
	$("#panel-item4").bind("mouseenter",function(){
		$("#panel-item4").css("background","rgb(247,247,247)");
		$("#angle4").css({
			"display":"inline-block"
		});
	});
	$("#panel-item4").bind("mouseleave",function(){
		$("#panel-item4").css("background","rgba(255,255,255,.97)");
		$("#angle4").css({
			"display":"none"
		});
	});

});
